id = "local/nix-status"
name = "Nix Status"
version = "0.2.0"
plugin_api = 24
author = "mindnbytes"
dependencies = ["nix"]

[[service]]
id = "service"
entry = "service.luau"

[[widget]]
id = "status"
entry = "widget.luau"

[[panel]]
id = "details"
entry = "panel.luau"
placement = "attached"
open_near_click = true
